# Generated by Django 2.1 on 2020-05-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='产品名字')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='省份')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='provice',
            field=models.ForeignKey(on_delete=True, to='app.Province', verbose_name='产品产地'),
        ),
    ]
