# Generated by Django 2.1 on 2020-05-02 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '特色管理', 'verbose_name_plural': '特色管理'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '省份管理', 'verbose_name_plural': '省份管理'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='provice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Province', verbose_name='产品产地'),
        ),
    ]
